[package]
name = "sapp-rs"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]

[dependencies]
hyper = {path="../../hyper"}
log = "0.3"
env_logger = "0.3"
route-recognizer = "0.1"
typemap = "0.3"
