[package]
name = "sapper"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]
license = "MIT"

[dependencies]
hyper = { git="https://github.com/hyperium/hyper.git", default-features=false }
#hyper = { git="https://github.com/hyperium/hyper.git" }
log = "*"
env_logger = "*"
route-recognizer = "*"
typemap = "*"
conduit-mime-types = "*"
lazy_static = "*"
