[package]
name = "sapper"
version = "0.1.0"
authors = ["Mike Tang <miketang84@outlook.com>"]
license = "MIT"

[dependencies]
#hyper = { git="https://github.com/hyperium/hyper.git", default-features=false }
hyper = "0.10.10"
log = "0.3.7"
env_logger = "0.4.2"
typemap = "0.3.3"
conduit-mime-types = "0.7.3"
lazy_static = "0.2.8"


